### Read all notes
GET http://localhost:3002/api/v2/notes/pg

### Create a new note
POST http://localhost:3002/api/v2/notes/pg
Content-Type: application/json

    # {
    #     "id": "1",
    #     "title": "New Project Idea PG-#1",
    #     "content": "Build an E-Commerce app for retail stores",
    #     "isCompleted": false
    # }

    # {
    #     "id": "2",
    #     "title": "Shopping List PG-#2",
    #     "content": "1. Milk\n2. Bread\n3. Eggs\n4. Coffee",
    #     "isCompleted": true
    # }

    # {
    #     "id": "3",
    #     "title": "System design study PG-#3",
    #     "content":
    #         "Study about refactoring the folder structure using Separation of Concerns",
    #     "isCompleted": false
    # }

    {
        "id": "4",
        "title": "Study React & NextJS PG-#4",
        "content": "Learn Front end, too",
        "isCompleted": false
    }

### Update a note
PUT http://localhost:3002/api/v2/notes/pg/
Content-Type: application/json

{
    "title": "New Project Idea #1 (Updated with NextJS)",
    "content": "Build an E-Commerce app using Nextjs and Tailwind",
    "isCompleted": true
}

### Delete a note
DELETE http://localhost:3002/api/v2/notes/pg/