### Read all products
GET http://localhost:3002/api/v2/products

### Create a new product
POST http://localhost:3002/api/v2/products
Content-Type: application/json

    # {
    #     "id": "1",
    #     "name": "MacBook 01",
    #     "price": 59900,
    #     "category": "Laptop",
    #     "inStock": true,
    #     "description": "Laptop for Good Dev"
    # }

    # {
    #     "id": "2",
    #     "name": "Keychron 02",
    #     "price": 3590,
    #     "category": "Keyboard",
    #     "inStock": true,
    #     "description": "Cool Mechanical keyboard"
    # }

    # {
    #     "id": "3",
    #     "name": "Sony Headphone 03",
    #     "price": 12990,
    #     "category": "Headphone",
    #     "inStock": false,
    #     "description": "Premium Headphone"
    # }

    # {
    #     "id": "4",
    #     "name": "Logitech Mouse Master 04",
    #     "price": 3990,
    #     "category": "Mouse",
    #     "inStock": true,
    #     "description": "Beautiful Mouse"
    # }

    {
        "name": "Nintendo Switch OLED 05",
        "price": 11990,
        "category": "Console",
        "inStock": true,
        "description": "Handheld gaming console with OLED screen"
    }

### Update a product
PUT http://localhost:3002/api/v2/products/6a0b196607dad1732e9f5dd5
Content-Type: application/json

{
    "name": "MacBook Pro Max 01b",
    "price": 129000,
    "category": "Laptop",
    "inStock": false,
    "description": "Super Laptop for Ultra Good Dev"
}

### Delete a product
DELETE http://localhost:3002/api/v2/products/6a0b197b07dad1732e9f5dd6